#Usando a base de dados BDEX3_REDESOCIAL, responda:
USE BDEX3_REDESOCIAL;

#1. Exibir todas as informações da tabela `USUARIOS`.
SHOW TABLES FROM BDEX3_REDESOCIAL;
SELECT *
FROM USUARIOS;
#2. Mostrar os nomes, sobrenomes e e-mails de todos os usuários.
#DESC USUARIOS;
SELECT CONCAT_WS(' ', NOME_USUARIO, SOBRENOME) AS NOME_COMPLETO, EMAIL FROM USUARIOS;
#3. Listar os nomes e descrições de todos os grupos.
SELECT NOME_GRUPO, DESCRICAO FROM GRUPOS;
#4. Exibir os detalhes das postagens: ID da postagem, texto, data e hora, e o nome do usuário que postou.
#DESC POSTAGENS;
SELECT 
POST.ID_POST, POST.TEXTO, POST.DATA_HORA, 
concat_ws(' ', USER.NOME_USUARIO, USER.SOBRENOME) AS USUARIO
FROM POSTAGENS POST
JOIN USUARIOS USER
ON POST.USUARIO = USER.ID_USUARIO;
#5. Listar o nome dos usuários e a quantidade de postagens que cada um fez.
SELECT
CONCAT_WS(' ', USER.NOME_USUARIO, USER.SOBRENOME) AS USUARIO,
COUNT(POST.ID_POST) AS POSTS
FROM POSTAGENS AS POST
JOIN USUARIOS AS USER
ON POST.USUARIO = USER.ID_USUARIO
GROUP BY USUARIO;
#6. Mostrar os nomes dos usuários que fizeram comentários em 2024.
DESC COMENTARIOS;
SELECT
CONCAT_WS(' ', USER.NOME_USUARIO, USER.SOBRENOME) AS USUARIO,
COUNT(COMT.ID_COMENTARIO) AS QTDE_COMENTARIOS
FROM COMENTARIOS AS COMT
RIGHT JOIN USUARIOS AS USER
ON COMT.USUARIO = USER.ID_USUARIO
WHERE YEAR(DATAHORA) = 2024
GROUP BY USUARIO;
#7. Listar todos os grupos, ordenados pelo nome do grupo de A a Z.
SELECT 
GRPO.NOME_GRUPO
FROM GRUPOS AS GRPO
ORDER BY NOME_GRUPO;
#8. Mostrar os nomes dos grupos que têm a palavra "Tecnologia" na descrição.
SELECT NOME_GRUPO
FROM GRUPOS
WHERE DESCRICAO LIKE '%TECNOLOGIA';
#9. Exibir os detalhes dos comentários: ID do comentário, texto, data e hora, nome do usuário que comentou e ID da postagem comentada.
SELECT
CONCAT_WS(' ', USER.NOME_USUARIO, USER.SOBRENOME) AS USUARIO,
COMT.ID_COMENTARIO, COMT.TEXTO, COMT.DATAHORA, COMT.POST
FROM COMENTARIOS AS COMT
JOIN USUARIOS AS USER
ON USER.ID_USUARIO = COMT.USUARIO
GROUP BY USUARIO;
#10. Para cada postagem, mostrar o ID da postagem e a quantidade de comentários.
SELECT 
POST.ID_POST, COUNT(COMT.ID_COMENTARIO) AS QTD_COMENTARIO
FROM COMENTARIOS AS COMT
RIGHT JOIN POSTAGENS AS POST
ON COMT.POST = POST.ID_POST
GROUP BY POST.ID_POST;
#11. Contar quantos seguidores cada usuário possui.
DESC SEGUIDORES_USUARIOS;
SELECT
USER.NOME_USUARIO, COUNT(SEG.SEGUIDOR) AS QTD_SEGUIDORES
FROM SEGUIDORES_USUARIOS AS SEG
JOIN USUARIOS AS USER
ON SEG.USUARIO = USER.ID_USUARIO
GROUP BY NOME_USUARIO;
#12. Listar os nomes dos usuários que pertencem ao grupo "Desenvolvimento".

#13. Mostrar o nome dos usuários e a data e hora da última postagem que eles fizeram.
SELECT CONCAT_WS(' ', USER.NOME_USUARIO, USER.SOBRENOME) AS USUARIO,
MAX(POST.DATA_HORA) AS ULTIMO_POST
FROM USUARIOS AS USER
LEFT JOIN POSTAGENS AS POST
ON USER.ID_USUARIO = POST.USUARIO
GROUP BY USUARIO;
#14. Contar quantas postagens cada usuário fez.
SELECT 
CONCAT_WS(' ', USER.NOME_USUARIO, USER.SOBRENOME) AS USUARIO,
COUNT(POST.ID_POST) AS QTD_POSTAGEM
FROM POSTAGENS AS POST
JOIN USUARIOS AS USER
ON USER.ID_USUARIO = POST.USUARIO
GROUP BY USUARIO;
#15. Para cada grupo, exibir o nome do grupo e a quantidade de usuários que pertencem a ele.
SELECT
GRP.NOME_GRUPO, COUNT(USER.ID_USUARIO) AS QTD_MEMBROS
FROM USUARIOS_GRUPOS AS USGP
JOIN GRUPOS AS GRP
ON GRP.ID_GRUPO = USGP.GRUPO
JOIN USUARIOS AS USER
ON USER.ID_USUARIO = USGP.USUARIO
GROUP BY GRP.NOME_GRUPO;