-- 1 PASSO: CRIAR O ESQUEMA DE BANCO DE DADOS
-- CREATE DATABASE IF NOT EXISTS LIVRARIA; OU
CREATE SCHEMA IF NOT EXISTS LIVRARIA_CC1MB;

-- 2 PASSO: INFORMAR QUAL BASE DE DADOS OU ESQUEMA SERÁ UTILIZADO
USE LIVRARIA_CC1MB;

-- 3 PASSO: CRIAR AS TABELAS DE DADOS COM SEUS ATRIBUTOS
-- CRIAR PRIMEIRO AS TABELAS QUE NÃO POSSUEM CHAVES ESTRANGEIRAS;

CREATE TABLE IF NOT EXISTS AUTORES(
ID_AUTOR INT,
NOME VARCHAR(45),
NACIONALIDADE VARCHAR(30),
PRIMARY KEY(ID_AUTOR) -- EM CASO DE COMPOSTAS, UTILIZAR ESSA RESTRIÇÃO
);


CREATE TABLE IF NOT EXISTS EMPRESTIMOS(
ID_EMP INT PRIMARY KEY,
DATA_EMP DATE,
DATA_DEV DATE,
);

CREATE TABLE IF NOT EXISTS EDITORAS(
ID_EDITORAS INT PRIMARY KEY,
NOME VARCHAR(45),
RUA VARCHAR(45),
NUMERO INT,
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
UF CHAR(2),
PAIS VARCHAR(50),
CEP VARCHAR(9));


CREATE TABLE IF NOT EXISTS LIVROS(
ISBN VARCHAR(12) PRIMARY KEY,
TITULO VARCHAR(30),
ANO YEAR,
EDITORA INT,
CONSTRAINT LIVRO_EDITORA FOREIGN KEY (EDITORA) REFERENCES EDITORAS(ID_EDITORAS),
);

-- ENTIDADES ASSOCIATIVAS
CREATE TABLE IF NOT EXISTS LIVROS_AUTORES(
ISBN VARCHAR(12),
AUTOR INT,
PRIMARY KEY (ISBN, AUTOR),
CONSTRAINT LIV_AUT FOREIGN KEY (ISBN) REFERENCES LIVROS (ISBN),
CONSTRAINT AUT_LIV FOREIGN KEY (AUTOR) REFERENCES AUTORES (ID_AUTOR));

CREATE TABLE IF NOT EXISTS EMP_LIVROS(
EMPRESTIMO INT,
ISBN VARCHAR(12),
PRIMARY KEY(EMPRESTIMO, ISBN),
CONSTRAINT LIV_EMP FOREIGN KEY (ISBN) REFERENCES LIVROS(ISBN),
CONSTRAINT EMP_LIV FOREIGN KEY (EMPRESTIMOS) REFERENCES EMPRESTIMO(ID_EMPRESTIMOS)
