#1
SELECT * FROM USUARIOS;
#2
SELECT NOME_USUARIO, SOBRENOME, EMAIL FROM USUARIOS;
#3
SELECT NOME_GRUPO, DESCRICAO FROM GRUPOS;
#4
SELECT ID_POST, TEXTO, DATA_HORA, USUARIOS.NOME_USUARIO
FROM POSTAGENS
INNER JOIN USUARIOS ON POSTAGENS.USUARIO = USUARIOS.ID_USUARIO
GROUP BY USUARIOS.ID_USUARIO, USUARIOS.NOME_USUARIO;
#5
SELECT USUARIOS.NOME_USUARIO, COUNT(*) AS QUANTIDADE_POSTAGEM
FROM POSTAGENS
INNER JOIN USUARIOS ON POSTAGENS.USUARIO = USUARIOS.ID_USUARIO
GROUP BY USUARIOS.ID_USUARIO, USUARIOS.NOME_USUARIO;
#6
SELECT NOME_USUARIO FROM USUARIOS INNER JOIN COMENTARIOS ON USUARIOS.ID_USUARIO = COMENTARIOS.USUARIO WHERE YEAR(DATAHORA) = 2024;
#7
SELECT *
FROM GRUPOS 
ORDER BY NOME_GRUPO ASC;
#8
SELECT NOME_GRUPO FROM GRUPOS WHERE DESCRICAO LIKE '%Tecnologia%';
#9
SELECT ID_COMENTARIO, TEXTO, DATAHORA, USUARIOS.NOME_USUARIO AS NOME_DO_USUARIO, POST FROM COMENTARIOS
INNER JOIN USUARIOS ON COMENTARIOS.USUARIO = USUARIOS.ID_USUARIO;
#10
SELECT p.ID_POST, COUNT(c.ID_COMENTARIO) AS QUANTIDADE_DE_COMENTARIOS
FROM POSTAGENS p
LEFT JOIN COMENTARIOS c ON p.ID_POST = c.POST
GROUP BY p.ID_POST;
#11
SELECT SEGUIDOR AS ID_DO_USUARIO, COUNT(*) AS QUANTIDADE_DE_SEGUIDORES
FROM SEGUIDORES_USUARIOS
GROUP BY SEGUIDOR;
#12
SELECT USUARIOS.NOME_USUARIO 
FROM USUARIOS
INNER JOIN USUARIOS_GRUPOS ON USUARIOS.ID_USUARIO = USUARIOS_GRUPOS.USUARIO
INNER JOIN GRUPOS ON USUARIOS_GRUPOS.GRUPO = GRUPOS.ID_GRUPO
WHERE GRUPOS.NOME_GRUPO = 'Desenvolvimento';
#13
SELECT U.NOME_USUARIO, P.DATA_HORA AS DATA_HORA_ULTIMA_POSTAGEM
FROM USUARIOS U
LEFT JOIN (
    SELECT USUARIO, MAX(DATA_HORA) AS DATA_HORA
    FROM POSTAGENS
    GROUP BY USUARIO
) P ON U.ID_USUARIO = P.USUARIO;
#14
SELECT USUARIOS.ID_USUARIO, USUARIOS.NOME_USUARIO, COUNT(POSTAGENS.ID_POST) AS QUANTIDADE_DE_POSTAGENS
FROM USUARIOS
LEFT JOIN POSTAGENS ON USUARIOS.ID_USUARIO = POSTAGENS.USUARIO
GROUP BY USUARIOS.ID_USUARIO, USUARIOS.NOME_USUARIO;
#15
SELECT G.NOME_GRUPO, COUNT(UG.USUARIO) AS QUANTIDADE_DE_USUARIOS
FROM GRUPOS G
LEFT JOIN USUARIOS_GRUPOS UG ON G.ID_GRUPO = UG.GRUPO
GROUP BY G.NOME_GRUPO;

